version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://backend:8000
      - REACT_APP_API_VERSION=v1
    depends_on:
      - backend
    networks:
      - financial-mediator

networks:
  financial-mediator:
    external: true
