services:
  backend:
    build:
      context: ./
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - database
    env_file:
      - ./.env
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    init: true
    depends_on:
      - backend
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  db_data: