version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=financialmediator.settings.local
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/financialmediator
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - JWT_SECRET_KEY=your-secret-key
      - OTEL_SERVICE_NAME=financialmediator
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - EMAIL_HOST=smtp.example.com
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=true
      - EMAIL_HOST_USER=noreply@example.com
      - EMAIL_HOST_PASSWORD=your-email-password
      - DEFAULT_FROM_EMAIL=noreply@example.com
      - CORS_ORIGIN_WHITELIST=http://localhost:3000,https://example.com
      - RATE_LIMIT_REQUESTS=100
      - RATE_LIMIT_DURATION=60
      - RATE_LIMIT_BUCKET_SIZE=1000
      - HEALTH_CHECK_TIMEOUT=30
      - HEALTH_CHECK_INTERVAL=10
      - HEALTH_CHECK_FAILURE_THRESHOLD=3
    depends_on:
      - db
      - redis
    networks:
      - financialmediator_network

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=financialmediator
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - financialmediator_network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - financialmediator_network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: celery -A financialmediator worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=financialmediator.settings.local
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
    networks:
      - financialmediator_network

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: celery -A financialmediator beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=financialmediator.settings.local
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
    networks:
      - financialmediator_network

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "8888:8888"  # Prometheus metrics
      - "8889:8889"  # Prometheus metrics (internal)
      - "13133:13133"  # Health checks
      - "55681:55681"  # pprof
    volumes:
      - ./otel-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - financialmediator_network

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  financialmediator_network:
    driver: bridge
