apiVersion: v1
kind: Secret
metadata:
  name: financialmediator-secrets
  labels:
    app: financialmediator
type: Opaque
data:
  # Django secret key
  SECRET_KEY: your-base64-encoded-secret-key
  
  # Database credentials
  DATABASE_PASSWORD: your-base64-encoded-password
  
  # Redis password
  REDIS_PASSWORD: your-base64-encoded-redis-password
  
  # Email credentials
  EMAIL_HOST_PASSWORD: your-base64-encoded-email-password
  
  # JWT secret key
  JWT_SECRET_KEY: your-base64-encoded-jwt-secret-key
  
  # OpenTelemetry credentials
  OTEL_EXPORTER_OTLP_HEADERS: your-base64-encoded-otel-headers
  
  # Other sensitive values
  AWS_ACCESS_KEY_ID: your-base64-encoded-aws-access-key
  AWS_SECRET_ACCESS_KEY: your-base64-encoded-aws-secret-key
