apiVersion: v1
kind: Secret
metadata:
  name: financialmediator-secrets
  namespace: default
  labels:
    app: financialmediator
    role: secrets
type: Opaque
data:
  # Django Secret Key
  DJANGO_SECRET_KEY: ""  # Base64 encoded
  
  # Database Password
  DATABASE_PASSWORD: ""  # Base64 encoded
  
  # Redis Password
  REDIS_PASSWORD: ""  # Base64 encoded
  
  # JWT Secret Key
  JWT_SECRET_KEY: ""  # Base64 encoded
  
  # Email Password
  EMAIL_HOST_PASSWORD: ""  # Base64 encoded
  
  # AWS Secrets
  AWS_ACCESS_KEY_ID: ""  # Base64 encoded
  AWS_SECRET_ACCESS_KEY: ""  # Base64 encoded
  
  # OpenTelemetry Headers
  OTEL_EXPORTER_OTLP_HEADERS: ""  # Base64 encoded
  
  # Database URL
  DATABASE_URL: ""  # Base64 encoded
  
  # Celery Broker URL
  CELERY_BROKER_URL: ""  # Base64 encoded
  
  # Celery Result Backend
  CELERY_RESULT_BACKEND: ""  # Base64 encoded
  
  # Redis URL
  REDIS_URL: ""  # Base64 encoded
