apiVersion: v1
kind: Secret
metadata:
  name: financialmediator-secrets
  labels:
    app: financialmediator
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:5432/{{ .Values.database.name }}"
  REDIS_URL: "redis://{{ .Values.redis.host }}:6379"
  CELERY_BROKER_URL: "redis://{{ .Values.redis.host }}:6379/0"
  CELERY_RESULT_BACKEND: "redis://{{ .Values.redis.host }}:6379/1"
  SECRET_KEY: "{{ .Values.django.secretKey }}"
  DEBUG: "{{ .Values.django.debug }}"
  ALLOWED_HOSTS: "{{ .Values.django.allowedHosts }}"
  CORS_ALLOWED_ORIGINS: "{{ .Values.django.corsOrigins }}"
  EMAIL_BACKEND: "{{ .Values.email.backend }}"
  EMAIL_HOST: "{{ .Values.email.host }}"
  EMAIL_PORT: "{{ .Values.email.port }}"
  EMAIL_USE_TLS: "{{ .Values.email.useTLS }}"
  EMAIL_HOST_USER: "{{ .Values.email.user }}"
  EMAIL_HOST_PASSWORD: "{{ .Values.email.password }}"
  RATE_LIMIT_WINDOW: "{{ .Values.rateLimit.window }}"
  RATE_LIMIT_REQUESTS: "{{ .Values.rateLimit.requests }}"
  LOG_LEVEL: "{{ .Values.logging.level }}"
  LOG_FILE: "{{ .Values.logging.file }}"
  HEALTH_CHECK_INTERVAL: "{{ .Values.healthCheck.interval }}"
  HEALTH_CHECK_TIMEOUT: "{{ .Values.healthCheck.timeout }}"
