apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  labels:
    app: financialmediator
type: Opaque
stringData:
  database_url: postgres://postgres:your-password@postgres:5432/financialmediator

---

apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  labels:
    app: financialmediator
type: Opaque
stringData:
  redis_url: redis://redis:6379/0

---

apiVersion: v1
kind: Secret
metadata:
  name: celery-secrets
  labels:
    app: financialmediator
type: Opaque
stringData:
  broker_url: redis://redis:6379/0
  result_backend: redis://redis:6379/0

---

apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  labels:
    app: financialmediator
type: Opaque
stringData:
  secret_key: your-django-secret-key-here
