apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: financialmediator
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /c/Users/Dell/FinancialMediator/data/postgres
    type: Directory
