apiVersion: v1
kind: Service
metadata:
  name: financialmediator
  namespace: financialmediator
spec:
  selector:
    app: financialmediator
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
