# Database Configuration
database:
  user: "financialmediator"
  password: "{{ .Values.secrets.databasePassword }}"
  host: "postgres"
  name: "financialmediator"

# Redis Configuration
redis:
  host: "redis"

# Django Configuration
django:
  secretKey: "{{ .Values.secrets.djangoSecretKey }}"
  debug: "False"
  allowedHosts: "nabilwealth.com,localhost,127.0.0.1"
  corsOrigins: "https://nabilwealth.com,http://localhost:8000"

# Email Configuration
email:
  backend: "django.core.mail.backends.smtp.EmailBackend"
  host: "smtp.gmail.com"
  port: "587"
  useTLS: "True"
  user: "{{ .Values.secrets.emailUser }}"
  password: "{{ .Values.secrets.emailPassword }}"

# Rate Limiting Configuration
rateLimit:
  window: "60"
  requests: "100"

# Logging Configuration
logging:
  level: "INFO"
  file: "/var/log/financialmediator/app.log"

# Health Check Configuration
healthCheck:
  interval: "30"
  timeout: "5"

# Secrets (These should be encrypted in a real environment)
secrets:
  databasePassword: "your-secure-database-password"
  djangoSecretKey: "your-secure-django-secret-key"
  emailUser: "your-email@example.com"
  emailPassword: "your-secure-email-password"
