apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  requirements.txt: |
    Django>=4.2.0
    psycopg2-binary>=2.9.0
    redis>=4.5.0
    celery>=5.3.0
    uwsgi>=2.0.20
    djangorestframework>=3.14.0
    django-cors-headers>=4.2.0
    python-dotenv>=1.0.0
    django-environ>=0.10.0
    django-celery-beat>=2.5.0
    django-celery-results>=2.4.0
    django-health-check>=3.19.0
    django-redis>=5.3.0
    django-filter>=23.2
    drf-spectacular>=0.27.0
    drf-yasg>=1.21.0
    python-jose[cryptography]>=3.3.0
    django-rest-auth>=0.9.5
    django-allauth>=0.53.0
    social-auth-app-django>=5.2.0
    django-cors-headers>=4.2.0
    django-health-check>=3.19.0
    django-redis>=5.3.0
    django-filter>=23.2
    drf-spectacular>=0.27.0
    drf-yasg>=1.21.0
    python-jose[cryptography]>=3.3.0
    django-rest-auth>=0.9.5
    django-allauth>=0.53.0
    social-auth-app-django>=5.2.0
  uwsgi.ini: |
    [uwsgi]
    http = 0.0.0.0:8000
    module = banking_project.wsgi:application
    master = true
    processes = 6
    threads = 2
    vacuum = true
    die-on-term = true
    enable-threads = true
    max-requests = 10000
    buffer-size = 32768
    harakiri = 120
    lazy-apps = true
    thunder-lock = true
    post-buffering = 8192
    stats = 127.0.0.1:9191

    # Logging
    log-4xx = true
    log-5xx = true
    disable-logging = true
    log-slow = true
    log-slow-timeout = 30

    # Memory and performance optimizations
    reload-on-rss = 2048
    max-worker-lifetime = 3600
    reload-mercy = 10
    worker-reload-mercy = 10
    memory-report = true
    cheaper-algo = spare
    cheaper = 2
    cheaper-initial = 4
    cheaper-step = 1
  financialmediator-config: |
    # Django settings
    DJANGO_SETTINGS_MODULE: financialmediator.settings.production
    ALLOWED_HOSTS: "*"
    
    # Database settings
    DATABASE_URL: postgresql://postgres:postgres@postgres:5432/financialmediator
    
    # Redis settings
    REDIS_URL: redis://redis:6379/0
    
    # Celery settings
    CELERY_BROKER_URL: redis://redis:6379/0
    CELERY_RESULT_BACKEND: redis://redis:6379/1
    
    # JWT settings
    JWT_SECRET_KEY: your-secret-key
    JWT_EXPIRE_MINUTES: "30"
    JWT_REFRESH_DAYS: "7"
    
    # OpenTelemetry settings
    OTEL_SERVICE_NAME: financialmediator
    OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    OTEL_EXPORTER_OTLP_INSECURE: "true"
    
    # Logging settings
    LOG_LEVEL: INFO
    
    # Security settings
    SECURE_SSL_REDIRECT: "true"
    SESSION_COOKIE_SECURE: "true"
    CSRF_COOKIE_SECURE: "true"
    
    # Email settings
    EMAIL_HOST: smtp.example.com
    EMAIL_PORT: "587"
    EMAIL_USE_TLS: "true"
    DEFAULT_FROM_EMAIL: noreply@example.com
    
    # CORS settings
    CORS_ORIGIN_WHITELIST: "['http://localhost:3000', 'https://example.com']"
    
    # Rate limiting settings
    RATE_LIMIT_REQUESTS: "100"
    RATE_LIMIT_DURATION: "60"
    RATE_LIMIT_BUCKET_SIZE: "1000"
    
    # Health check settings
    HEALTH_CHECK_TIMEOUT: "30"
    HEALTH_CHECK_INTERVAL: "10"
    HEALTH_CHECK_FAILURE_THRESHOLD: "3"
