apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  requirements.txt: |
    Django>=4.2.0
    psycopg2-binary>=2.9.0
    redis>=4.5.0
    celery>=5.3.0
    uwsgi>=2.0.20
    djangorestframework>=3.14.0
    django-cors-headers>=4.2.0
    python-dotenv>=1.0.0
    django-environ>=0.10.0
    django-celery-beat>=2.5.0
    django-celery-results>=2.4.0
    django-health-check>=3.19.0
    django-redis>=5.3.0
    django-filter>=23.2
    drf-spectacular>=0.27.0
    drf-yasg>=1.21.0
    python-jose[cryptography]>=3.3.0
    django-rest-auth>=0.9.5
    django-allauth>=0.53.0
    social-auth-app-django>=5.2.0
    django-cors-headers>=4.2.0
    django-health-check>=3.19.0
    django-redis>=5.3.0
    django-filter>=23.2
    drf-spectacular>=0.27.0
    drf-yasg>=1.21.0
    python-jose[cryptography]>=3.3.0
    django-rest-auth>=0.9.5
    django-allauth>=0.53.0
    social-auth-app-django>=5.2.0
  uwsgi.ini: |
    [uwsgi]
    http = 0.0.0.0:8000
    module = banking_project.wsgi:application
    master = true
    processes = 6
    threads = 2
    vacuum = true
    die-on-term = true
    enable-threads = true
    max-requests = 10000
    buffer-size = 32768
    harakiri = 120
    lazy-apps = true
    thunder-lock = true
    post-buffering = 8192
    stats = 127.0.0.1:9191

    # Logging
    log-4xx = true
    log-5xx = true
    disable-logging = true
    log-slow = true
    log-slow-timeout = 30

    # Memory and performance optimizations
    reload-on-rss = 2048
    max-worker-lifetime = 3600
    reload-mercy = 10
    worker-reload-mercy = 10
    memory-report = true
    cheaper-algo = spare
    cheaper = 2
    cheaper-initial = 4
    cheaper-step = 1
  financialmediator-config: |
    # Django Settings
    DJANGO_SETTINGS_MODULE: financialmediator.settings.production
    DEBUG: "false"
    ALLOWED_HOSTS: "financialmediator.example.com"
    
    # Database Settings
    DATABASE_URL: "postgresql://postgres:postgres@postgresql:5432/financialmediator"
    DATABASE_NAME: financialmediator
    DATABASE_USER: postgres
    DATABASE_PASSWORD: postgres
    DATABASE_HOST: postgresql
    DATABASE_PORT: "5432"
    
    # Redis Settings
    REDIS_URL: "redis://redis:6379/0"
    REDIS_PASSWORD: ""
    
    # Celery Settings
    CELERY_BROKER_URL: "redis://redis:6379/0"
    CELERY_RESULT_BACKEND: "redis://redis:6379/1"
    
    # JWT Settings
    JWT_SECRET_KEY: ""
    JWT_ACCESS_TOKEN_LIFETIME_MINUTES: "60"
    JWT_REFRESH_TOKEN_LIFETIME_DAYS: "7"
    
    # OpenTelemetry Settings
    OTEL_SERVICE_NAME: financialmediator
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
    OTEL_EXPORTER_OTLP_INSECURE: "true"
    
    # Email Settings
    EMAIL_HOST: smtp.example.com
    EMAIL_PORT: "587"
    EMAIL_USE_TLS: "true"
    EMAIL_HOST_USER: noreply@example.com
    DEFAULT_FROM_EMAIL: noreply@example.com
    
    # CORS Settings
    CORS_ORIGIN_WHITELIST: "http://localhost:3000,https://example.com"
    
    # Rate Limiting Settings
    RATE_LIMIT_REQUESTS: "100"
    RATE_LIMIT_DURATION: "60"
    RATE_LIMIT_BUCKET_SIZE: "1000"
    
    # Health Check Settings
    HEALTH_CHECK_TIMEOUT: "30"
    HEALTH_CHECK_INTERVAL: "10"
    HEALTH_CHECK_FAILURE_THRESHOLD: "3"
    
    # AWS Settings (if using AWS)
    AWS_ACCESS_KEY_ID: ""
    AWS_SECRET_ACCESS_KEY: ""
    AWS_STORAGE_BUCKET_NAME: ""
    
    # Security Settings
    SECURE_SSL_REDIRECT: "true"
    SESSION_COOKIE_SECURE: "true"
    CSRF_COOKIE_SECURE: "true"
    
    # Logging Settings
    LOG_LEVEL: INFO
    LOG_FILE_PATH: /var/log/financialmediator/app.log
    
    # Cache Settings
    CACHE_KEY_PREFIX: financialmediator
    CACHE_MIDDLEWARE_SECONDS: "60"
    
    # Django REST Framework Settings
    REST_FRAMEWORK_DEFAULT_THROTTLE_CLASSES: "rest_framework.throttling.AnonRateThrottle,rest_framework.throttling.UserRateThrottle"
    REST_FRAMEWORK_DEFAULT_THROTTLE_RATES: "anon:100/day,user:1000/day"
    
    # Django Debug Toolbar Settings
    DEBUG_TOOLBAR_CONFIG_SHOW_TOOLBAR_CALLBACK: "lambda _request: DEBUG"
    
    # Django REST Framework Spectacular Settings
    SPECTACULAR_SETTINGS_TITLE: FinancialMediator API
    SPECTACULAR_SETTINGS_VERSION: "1.0.0"
    SPECTACULAR_SETTINGS_SERVE_INCLUDE_SCHEMA: "false"
    SPECTACULAR_SETTINGS_SWAGGER_UI_SETTINGS: "deepLinking:true,persistAuthorization:true,displayOperationId:true"
    
    # Django REST Framework Simple JWT Settings
    SIMPLE_JWT_ACCESS_TOKEN_LIFETIME: "00:15:00"
    SIMPLE_JWT_REFRESH_TOKEN_LIFETIME: "7 00:00:00"
