apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: default
  labels:
    app: redis
    role: config
data:
  redis.conf: |
    # Redis configuration
    
    # General
    daemonize no
    pidfile /var/run/redis/redis.pid
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    
    # Logging
    loglevel notice
    logfile /var/log/redis/redis.log
    
    # Data persistence
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data
    
    # Replication
    replica-serve-stale-data yes
    replica-read-only yes
    replica-priority 100
    min-replicas-to-write 0
    min-replicas-max-lag 10
    
    # Security
    requirepass ${REDIS_PASSWORD}
    rename-command FLUSHALL ""
    rename-command FLUSHDB ""
    
    # Memory management
    maxmemory 1gb
    maxmemory-policy volatile-lru
    maxmemory-samples 5
    
    # Append-only mode
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes
    
    # Slow log
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    
    # Memory diagnostics
    activerehashing yes
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    
    # Cluster configuration
    cluster-enabled no
    cluster-config-file nodes.conf
    cluster-node-timeout 15000
    
    # Notification system
    notify-keyspace-events ""
    
    # Advanced configuration
    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    list-max-ziplist-size -2
    list-compress-depth 0
    set-max-intset-entries 512
    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64
    hll-sparse-max-bytes 3000
    stream-node-max-bytes 4096
    stream-node-max-entries 100
    
    # AOF rewrite buffer limit
    aof-rewrite-incremental-fsync yes
    
    # Latency monitoring
    latency-monitor-threshold 0
    
    # Event notifications
    notify-keyspace-events ""
    
    # Lua script cache
    lua-time-limit 5000
    
    # Client timeout
    client-timeout 0
    
    # TCP backlog
    tcp-backlog 511
    
    # TCP keepalive
    tcp-keepalive 300
    
    # Client output buffer limits
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    
    # Client timeout
    client-timeout 0
    
    # TCP backlog
    tcp-backlog 511
    
    # TCP keepalive
    tcp-keepalive 300
    
    # Client output buffer limits
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    
    # Client timeout
    client-timeout 0
    
    # TCP backlog
    tcp-backlog 511
    
    # TCP keepalive
    tcp-keepalive 300
    
    # Client output buffer limits
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
