# Application Configuration
app:
  name: financialmediator
  namespace: financial-mediator
  replicas: 1
  port: 8000

# Resource Configuration
resources:
  memory:
    request: "256Mi"
    limit: "512Mi"
  cpu:
    request: "200m"
    limit: "500m"

# Image Configuration
image:
  repository: docker-desktop:5000/financial-mediator
  tag: latest

# Service Configuration
service:
  type: LoadBalancer
  port: 80
  target_port: 8000
