apiVersion: apps/v1
kind: Deployment
metadata:
  name: financialmediator
  namespace: financial-mediator
  labels:
    app: financialmediator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: financialmediator
  template:
    metadata:
      labels:
        app: financialmediator
    spec:
      containers:
      - name: financialmediator
        image: docker-desktop:5000/financial-mediator:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: financialmediator-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        volumeMounts:
        - name: static-volume
          mountPath: /app/static
        - name: media-volume
          mountPath: /app/media
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-pvc
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-pvc
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: financialmediator
  namespace: financial-mediator
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: financialmediator

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: financial-mediator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: financial-mediator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
