apiVersion: v1
kind: Service
metadata:
  name: {{service_name}}
  namespace: {{namespace}}
spec:
  type: {{service_type}}
  ports:
  - port: {{port}}
    targetPort: {{target_port}}
    protocol: TCP
  selector:
    app: {{app_name}}
