apiVersion: apps/v1
kind: Deployment
metadata:
  name: financialmediator
  namespace: default
  labels:
    app: financialmediator
    role: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: financialmediator
      role: web
  template:
    metadata:
      labels:
        app: financialmediator
        role: web
    spec:
      containers:
      - name: web
        image: financialmediator:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: financialmediator-config
        - secretRef:
            name: financialmediator-secrets
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "500m"
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /health/
            port: 8000
          failureThreshold: 30
          periodSeconds: 10
          timeoutSeconds: 1
          initialDelaySeconds: 0
        volumeMounts:
        - name: static-volume
          mountPath: /app/static
        - name: media-volume
          mountPath: /app/media
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-pvc
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-pvc
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      serviceAccountName: financialmediator-sa
      imagePullSecrets:
      - name: regcred
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 10
