apiVersion: apps/v1
kind: Deployment
metadata:
  name: financialmediator
  labels:
    app: financialmediator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financialmediator
  template:
    metadata:
      labels:
        app: financialmediator
    spec:
      containers:
      - name: financialmediator
        image: python:3.11-slim
        command: ["/bin/sh"]
        args: ["-c", "apt-get update && apt-get install -y --no-install-recommends python3-pip python3-dev build-essential gcc postgresql-client libpq-dev && pip3 install --upgrade pip && pip3 install --no-cache-dir -r /app/requirements.txt && python /app/manage.py migrate && uwsgi --ini /app/uwsgi.ini"]
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: financialmediator-secrets
        volumeMounts:
        - name: app-config
          mountPath: /app
        - name: app-files
          mountPath: /app/banking_project
        - name: app-volume
          mountPath: /app/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
      volumes:
      - name: app-config
        configMap:
          name: app-config
      - name: app-files
        configMap:
          name: app-files
      - name: app-volume
        emptyDir: {}
