apiVersion: apps/v1
kind: Deployment
metadata:
  name: financialmediator
  labels:
    app: financialmediator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financialmediator
  template:
    metadata:
      labels:
        app: financialmediator
    spec:
      containers:
      - name: financialmediator
        image: python:3.11-slim
        command: ["/bin/sh"]
        args: ["-c", "apt-get update && apt-get install -y --no-install-recommends python3-pip python3-dev build-essential gcc postgresql-client libpq-dev && pip3 install --upgrade pip && pip3 install --no-cache-dir -r /app/requirements.txt && python /app/manage.py migrate && uwsgi --ini /app/uwsgi.ini"]
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@postgres:5432/financialmediator
        - name: REDIS_URL
          value: redis://redis:6379
        - name: CELERY_BROKER_URL
          value: redis://redis:6379/0
        - name: CELERY_RESULT_BACKEND
          value: redis://redis:6379/1
        - name: SECRET_KEY
          value: "your-secret-key-change-in-production"
        - name: DEBUG
          value: "True"
        - name: ALLOWED_HOSTS
          value: "localhost,127.0.0.1,nabilwealth.com"
        - name: CORS_ALLOWED_ORIGINS
          value: "http://localhost:8000"
        volumeMounts:
        - name: app-config
          mountPath: /app
        - name: app-files
          mountPath: /app/banking_project
        - name: app-volume
          mountPath: /app/data
        - name: settings-volume
          mountPath: /app/banking_project/settings.py
          subPath: settings.py
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
      volumes:
      - name: app-config
        configMap:
          name: app-config
          items:
          - key: requirements.txt
            path: requirements.txt
          - key: uwsgi.ini
            path: uwsgi.ini
      - name: app-files
        configMap:
          name: app-files
          items:
          - key: manage.py
            path: manage.py
          - key: wsgi.py
            path: wsgi.py
          - key: urls.py
            path: urls.py
          - key: settings.py
            path: settings.py
      - name: app-volume
        emptyDir: {}
      - name: settings-volume
        configMap:
          name: app-files
          items:
          - key: settings.py
            path: settings.py
