apiVersion: v1
kind: Service
metadata:
  name: financialmediator
  namespace: default
  labels:
    app: financialmediator
    role: web
spec:
  type: LoadBalancer
  selector:
    app: financialmediator
    role: web
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8000
    protocol: TCP
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: health
    port: 8081
    targetPort: 8081
    protocol: TCP
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  healthCheckNodePort: 0
  publishNotReadyAddresses: false
status:
  loadBalancer: {}
