apiVersion: v1
kind: Service
metadata:
  name: financialmediator-service
  labels:
    app: financialmediator
spec:
  selector:
    app: financialmediator
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: financialmediator-external
  labels:
    app: financialmediator
spec:
  selector:
    app: financialmediator
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  type: NodePort
