apiVersion: v1
kind: Service
metadata:
  name: financialmediator
  labels:
    app: financialmediator
spec:
  selector:
    app: financialmediator
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: financialmediator-external
  labels:
    app: financialmediator
spec:
  selector:
    app: financialmediator
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer
