apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: default
  labels:
    app: postgresql
    role: database
spec:
  type: ClusterIP
  selector:
    app: postgresql
    role: database
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  healthCheckNodePort: 0
  publishNotReadyAddresses: false
  selector:
    app: postgresql
    role: database
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
