apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
  labels:
    app: redis
    role: cache
spec:
  type: ClusterIP
  selector:
    app: redis
    role: cache
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  healthCheckNodePort: 0
  publishNotReadyAddresses: false
  selector:
    app: redis
    role: cache
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
