name: Kubernetes Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: your-registry/financialmediator:latest
        cache-from: type=registry,ref=your-registry/financialmediator:latest
        cache-to: type=inline
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Deploy to EKS
      uses: aws-actions/amazon-eks-deploy@v3
      with:
        kubectl-version: "1.26.1"
        cluster-name: your-cluster-name
        region: us-east-1
        manifests: |
          k8s/deployments/django-deployment.yaml
          k8s/services/django-service.yaml
          k8s/secrets/secrets.yaml
          k8s/persistence/pvc.yaml
          k8s/hpa/hpa.yaml
        namespace: default
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-arn: ${{ secrets.EKS_ROLE_ARN }}
    
    - name: Wait for deployment
      run: |
        kubectl rollout status deployment/financialmediator
        kubectl get pods
