name: Kubernetes Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure Kubernetes
      run: |
        kubectl config set-context default
        kubectl config use-context default
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployments/django-deployment.yaml
        kubectl apply -f k8s/services/django-service.yaml
        kubectl apply -f k8s/secrets/secrets.yaml
        kubectl apply -f k8s/persistence/pvc.yaml
        kubectl apply -f k8s/hpa/hpa.yaml
    
    - name: Wait for deployment
      run: |
        kubectl rollout status deployment/financialmediator
        kubectl get pods
